### PR TITLE
Introduce new build system

### PR DESCRIPTION
**Pull request by fosslinux**
This build system is very different to the old build system, and is much
more inuitive.

It leverages a hand made configure script to generate the Makefile. The
listener is no longer auto-detected, unless specifically specified, and
no longer activated by default. That is not the place for a build system.
Along with the focus of moving to distribution repositiories, this 'feature'
is clearly unwanted by distributions.

Multiple listeners are now also supported, primarily for distributions.

Lastly, parallelism now works as well.

@hb9kns your input would be appreciated
@ryanakca How much less hostile is this to distributions such as Debian?

### CODE REVIEW

**Comment by ryanakca** [comment]
It's certainly nicer than having to manually patch the Makefile to set paths and ensure that CFLAGS gets respected :-)

A minor request: it might be nice to add a "none" listener to the configure script for distributions that want to provide support for multiple listeners, and so need to manually install the relevant files. This option already works as a fall-through, but it would be nice to have this as a documented option to avoid it getting lost in a future refactoring of the build system.

**Comment by fosslinux** [comment]
This supports a comma-separated list of listeners.

**Comment by fosslinux** [comment]
Note to myself: I need to fix CI for this too.

Hopefully pushing this weekend.

**Comment by ryanakca** [comment]
> This supports a comma-separated list of listeners.

I don't see this in the source for `configure`, and comma-separated lists don't seem to work (though maybe I'm missing something):

```
./configure \
        --gopherroot=/srv/gopher \
        --listener=systemd,inetd,xinetd \
        --prefix=/usr
checking for working compiler... cc
checking for install... /usr/bin/install
checking for listener... systemd,inetd,xinetd
The listener systemd,inetd,xinetd is not offically supported; continuing anyway.
```

**Comment by fosslinux** [comment]
well i thought i tried to make it work, maybe I didn't push it? will be looking into it

**Comment by fosslinux** [comment]
Release by the end of the year, I promise. Now that I am completely free after today until the end fo the year I have heaps of time to work on stuff.

**Comment by fosslinux** [comment]
Also @ryanakca is it ok for me to delete the debian packaging from this repository now?

**Comment by ryanakca** [comment]
> Also @ryanakca is it ok for me to delete the debian packaging from this repository now?

I see you've already done so, but yes, feel free to delete it!

**Pull request merged**
