### PR TITLE
fix 'make install-root' clobbering existing gophermaps

### PR DESCRIPTION
**Pull request by MustachedSquid**

### CODE REVIEW

**Comment by MustachedSquid** [comment]
This fixes #92

**Comment by MustachedSquid** [comment]
I actually messed this up

**Comment by tallship** [comment]
What?

Jun 17, 2022 7:26:31 AM Tomás Duarte ***@***.***>:

**Comment by MustachedSquid** [comment]
My apologies for this PR, this one was a mistake. I have made a new one which actually working [here.](https://github.com/gophernicus/gophernicus/pull/110)

**Pull request closed without merging**
